### ISSUE TITLE
No such file or directory: 'data/fiveK/train input .txt'

### ISSUE THREAD

**Issue by ChickenEating** [riversky2025/TITFormer#1]
下载的数据集中没有这个train input .txt文件，请问作者该如何解决

**Comment by riversky2025** [comment]
To improve runtime speed, it was stored in the   encodings.pt.

**Comment by riversky2025** [comment]
当前版本使用的是该图像转text模型：https://ankur3107.github.io/blogs/the-illustrated-image-captioning-using-transformers/ 进行生成。
